@echo off
echo installing...
echo Downloading nodejs...
curl https://nodejs.org/dist/v14.15.4/node-v14.15.4-x64.msi
set /p DUMMY=Hit ENTER to continue...
echo Installing required packages...
npm install discord.js
npm i discord-music-system
npm i nodemon
echo Starting bot...
start.bat
